import { Snowflake } from 'lucide-react'

export const Assets = {
  CHARACTER: 'assets/Character/Pro_Sword_and_Shield_Pack/Paladin_WProp_J_Nordstrom.fbx',
  // CHARACTER: 'assets/Character/IA_schoolgirl/IA.pmx',
  // CHARACTER: 'assets/Character/Fanny/Fanny2.glb',
  MAP: 'assets/Map/st._annes_episcopal_school.glb',
  ROOM: 'assets/Room/3D_Isometric_BEDROOM.glb',
  GRASS_TEXTURE: 'assets/Map/grass.jpg',
  ANIMATION: {
    // DRAW_SWORD_1: 'assets/Character/Pro_Sword_and_Shield_Pack/draw_sword_1.fbx',
    DRAW_SWORD_2: 'assets/Character/Pro_Sword_and_Shield_Pack/draw_sword_2.fbx',
    SHEATH_SWORD_1: 'assets/Character/Pro_Sword_and_Shield_Pack/sheath_sword_1.fbx',
    SHEATH_SWORD_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sheath_sword_2.fbx',
    SWORD_AND_SHIELD_180_TURN_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_180_turn_2.fbx',
    SWORD_AND_SHIELD_180_TURN: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_180_turn.fbx',
    SWORD_AND_SHIELD_ATTACK_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_attack_2.fbx',
    SWORD_AND_SHIELD_ATTACK_3: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_attack_3.fbx',
    // SWORD_AND_SHIELD_ATTACK_4: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_attack_4.fbx',
    SWORD_AND_SHIELD_ATTACK: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_attack.fbx',
    SWORD_AND_SHIELD_BLOCK_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_block_2.fbx',
    SWORD_AND_SHIELD_BLOCK_IDLE: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_block_idle.fbx',
    SWORD_AND_SHIELD_BLOCK: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_block.fbx',
    // SWORD_AND_SHIELD_CASTING_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_casting_2.fbx',
    SWORD_AND_SHIELD_CASTING: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_casting.fbx',
    // SWORD_AND_SHIELD_CROUCH_BLOCK_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_block_2.fbx',
    SWORD_AND_SHIELD_CROUCH_BLOCK_IDLE:
      'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_block_idle.fbx',
    SWORD_AND_SHIELD_CROUCH_BLOCK: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_block.fbx',
    SWORD_AND_SHIELD_CROUCH_IDLE: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_idle.fbx',
    SWORD_AND_SHIELD_CROUCH: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch.fbx',
    SWORD_AND_SHIELD_CROUCHING_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouching_2.fbx',
    SWORD_AND_SHIELD_CROUCHING_3: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouching_3.fbx',
    SWORD_AND_SHIELD_CROUCHING: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_crouching.fbx',
    SWORD_AND_SHIELD_DEATH_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_death_2.fbx',
    // SWORD_AND_SHIELD_DEATH: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_death.fbx',
    SWORD_AND_SHIELD_IDLE_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_idle_2.fbx',
    SWORD_AND_SHIELD_IDLE_3: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_idle_3.fbx',
    SWORD_AND_SHIELD_IDLE_4: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_idle_4.fbx',
    SWORD_AND_SHIELD_IDLE: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_idle.fbx',
    SWORD_AND_SHIELD_IMPACT_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_impact_2.fbx',
    SWORD_AND_SHIELD_IMPACT_3: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_impact_3.fbx',
    // SWORD_AND_SHIELD_IMPACT: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_impact.fbx',
    SWORD_AND_SHIELD_JUMP_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_jump_2.fbx',
    SWORD_AND_SHIELD_JUMP: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_jump.fbx',
    SWORD_AND_SHIELD_KICK: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_kick.fbx',
    SWORD_AND_SHIELD_POWER_UP: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_power_up.fbx',
    SWORD_AND_SHIELD_RUN_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_run_2.fbx',
    SWORD_AND_SHIELD_RUN: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_run.fbx',
    SWORD_AND_SHIELD_SLASH_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_2.fbx',
    SWORD_AND_SHIELD_SLASH_3: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_3.fbx',
    SWORD_AND_SHIELD_SLASH_4: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_4.fbx',
    // SWORD_AND_SHIELD_SLASH_5: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_5.fbx',
    SWORD_AND_SHIELD_SLASH: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_slash.fbx',
    SWORD_AND_SHIELD_STRAFE_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe_2.fbx',
    SWORD_AND_SHIELD_STRAFE_3: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe_3.fbx',
    SWORD_AND_SHIELD_STRAFE_4: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe_4.fbx',
    SWORD_AND_SHIELD_STRAFE: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe.fbx',
    SWORD_AND_SHIELD_TURN_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_turn_2.fbx',
    SWORD_AND_SHIELD_TURN: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_turn.fbx',
    SWORD_AND_SHIELD_WALK_2: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_walk_2.fbx',
    SWORD_AND_SHIELD_WALK: 'assets/Character/Pro_Sword_and_Shield_Pack/sword_and_shield_walk.fbx',
    SIT_TO_STAND: 'assets/Character/Pro_Sword_and_Shield_Pack/sit_to_stand.fbx',
    STAND_TO_SIT: 'assets/Character/Pro_Sword_and_Shield_Pack/stand_to_sit.fbx',
    SITTING_IDLE: 'assets/Character/Pro_Sword_and_Shield_Pack/sitting_idle.fbx',
    STANDING_MELEE_ATTACK_DOWNWARD: 'assets/Character/Pro_Sword_and_Shield_Pack/standing_melee_attack_downward.fbx',
    STANDING_MELEE_ATTACK_HORIZONTAL: 'assets/Character/Pro_Sword_and_Shield_Pack/standing_melee_attack_horizontal.fbx',
  },
  NPC: { SLIME: 'assets/Character/slime.glb' },
  ENEMY: {},
  CAMPFIRE: 'assets/Map/h_campfire.glb',
  CASTLE_WALL: 'assets/Map/castle_wall.glb',
  TENT: 'assets/Map/tent_modified.glb',
  WOOD_BLOCK: 'assets/Map/wood_chopping_trunk_base.glb',
  TREE: 'assets/Map/pine_tree.glb',

  TEXTURE: {
    STONE_RIVER: {
      ALBEDO_ROUGHNESS_METALNESS: 'assets/textures/ganges_river_pebbles_1k/ganges_river_pebbles_arm_1k.jpg',
      DIFFUSE: 'assets/textures/ganges_river_pebbles_1k/ganges_river_pebbles_diff_1k.jpg',
      HEIGHT: 'assets/textures/ganges_river_pebbles_1k/ganges_river_pebbles_disp_1k.jpg',
      NORMAL: 'assets/textures/ganges_river_pebbles_1k/ganges_river_pebbles_nor_gl_1k.jpg',
    },
    ROCK_MOSSY: {
      ALBEDO_ROUGHNESS_METALNESS: 'assets/textures/mossy_rock_1k/mossy_rock_arm_1k.jpg',
      DIFFUSE: 'assets/textures/mossy_rock_1k/mossy_rock_diff_1k.jpg',
      HEIGHT: 'assets/textures/mossy_rock_1k/mossy_rock_disp_1k.jpg',
      NORMAL: 'assets/textures/mossy_rock_1k/mossy_rock_nor_gl_1k.jpg',
    },
    ALLUVIAL_SOIL: {
      ALBEDO_ROUGHNESS_METALNESS: 'assets/textures/red_laterite_soil_stones_1k/red_laterite_soil_stones_arm_1k.jpg',
      DIFFUSE: 'assets/textures/red_laterite_soil_stones_1k/red_laterite_soil_stones_diff_1k.jpg',
      HEIGHT: 'assets/textures/red_laterite_soil_stones_1k/red_laterite_soil_stones_disp_1k.jpg',
      NORMAL: 'assets/textures/red_laterite_soil_stones_1k/red_laterite_soil_stones_nor_gl_1k.jpg',
    },
    GROUND: {
      ALBEDO_ROUGHNESS_METALNESS: 'assets/textures/brown_mud_leaves_01_1k/brown_mud_leaves_01_arm_1k.jpg',
      DIFFUSE: 'assets/textures/brown_mud_leaves_01_1k/brown_mud_leaves_01_diff_1k.jpg',
      HEIGHT: 'assets/textures/brown_mud_leaves_01_1k/brown_mud_leaves_01_disp_1k.jpg',
      NORMAL: 'assets/textures/brown_mud_leaves_01_1k/brown_mud_leaves_01_nor_gl_1k.jpg',
    },
    ROCK_WALL: {
      ALBEDO: 'assets/textures/GreyRock03_1K/GreyRock03_1K_AO.png',
      ROUGHNESS: 'assets/textures/GreyRock03_1K/GreyRock03_1K_Roughness.png',
      METALNESS: 'assets/textures/GreyRock03_1K/GreyRock03_1K_Metallic.png',
      DIFFUSE: 'assets/textures/GreyRock03_1K/GreyRock03_1K_BaseColor.png',
      HEIGHT: 'assets/textures/GreyRock03_1K/GreyRock03_1K_Height.png',
      NORMAL: 'assets/textures/GreyRock03_1K/GreyRock03_1K_Normal.png',
    },
    TOP_MOUNTAIN: {
      ALBEDO_ROUGHNESS_METALNESS: 'assets/textures/snow_02_1k/snow_02_arm_1k.jpg',
      DIFFUSE: 'assets/textures/snow_02_1k/snow_02_diff_1k.jpg',
      HEIGHT: 'assets/textures/snow_02_1k/snow_02_disp_1k.jpg',
      NORMAL: 'assets/textures/snow_02_1k/snow_02_nor_gl_1k.jpg',
    },
    GRASS: {
      ALBEDO: 'assets/textures/grass.jpg',
    },
    NOISE: {
      WATER_NOISE: 'assets/textures/noise/waterSurface_noise.png',
      PERLIN: 'assets/textures/noise/perlin.png',
    },
    FIRE: 'assets/textures/fire.png',
  },
  AUDIO: {
    BGM: {
      BGM_0: 'assets/audio/bgm/ethereal-ambient-269037.mp3',
      BGM_1: 'assets/audio/bgm/fantasy-158150.mp3',
      BGM_2: 'assets/audio/bgm/fantasy-354183.mp3',
      BGM_3: 'assets/audio/bgm/fantasy-classical-themes-132199.mp3',
      BGM_4: 'assets/audio/bgm/fantasy-forest-1-263881.mp3',
      BGM_5: 'assets/audio/bgm/fantasy-music-overture-orchestral-amp-choir-113620.mp3',
      BGM_6: 'assets/audio/bgm/game-setting-fantasy-142092.mp3',
    },
    SFX: {},
  },
  FONT: {
    // ROBOTO_SEMIBOLD_REGULAR: 'assets/font/Roboto/Roboto_SemiBold_Regular.json',
    ROBOTO_SEMIBOLD_REGULAR: 'assets/font/Roboto/Roboto_SemiBold_Regular.json',
  },
}
