export const Assets = {
  CHARACTER: 'assets/Pro_Sword_and_Shield_Pack/Paladin_WProp_J_Nordstrom.fbx',
  // CHARACTER: 'assets/IA_schoolgirl/IA.pmx',
  // CHARACTER: 'assets/Fanny/Fanny2.glb',
  MAP: 'assets/Map/st._annes_episcopal_school.glb',
  ROOM: 'assets/Room/3D_Isometric_BEDROOM.glb',
  GRASS_TEXTURE: 'assets/Map/grass.jpg',
  ANIMATION: {
    // DRAW_SWORD_1: 'assets/Pro_Sword_and_Shield_Pack/draw_sword_1.fbx',
    DRAW_SWORD_2: 'assets/Pro_Sword_and_Shield_Pack/draw_sword_2.fbx',
    SHEATH_SWORD_1: 'assets/Pro_Sword_and_Shield_Pack/sheath_sword_1.fbx',
    SHEATH_SWORD_2: 'assets/Pro_Sword_and_Shield_Pack/sheath_sword_2.fbx',
    SWORD_AND_SHIELD_180_TURN_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_180_turn_2.fbx',
    SWORD_AND_SHIELD_180_TURN: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_180_turn.fbx',
    SWORD_AND_SHIELD_ATTACK_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_attack_2.fbx',
    SWORD_AND_SHIELD_ATTACK_3: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_attack_3.fbx',
    // SWORD_AND_SHIELD_ATTACK_4: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_attack_4.fbx',
    SWORD_AND_SHIELD_ATTACK: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_attack.fbx',
    SWORD_AND_SHIELD_BLOCK_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_block_2.fbx',
    SWORD_AND_SHIELD_BLOCK_IDLE: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_block_idle.fbx',
    SWORD_AND_SHIELD_BLOCK: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_block.fbx',
    // SWORD_AND_SHIELD_CASTING_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_casting_2.fbx',
    SWORD_AND_SHIELD_CASTING: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_casting.fbx',
    // SWORD_AND_SHIELD_CROUCH_BLOCK_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_block_2.fbx',
    SWORD_AND_SHIELD_CROUCH_BLOCK_IDLE: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_block_idle.fbx',
    SWORD_AND_SHIELD_CROUCH_BLOCK: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_block.fbx',
    SWORD_AND_SHIELD_CROUCH_IDLE: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch_idle.fbx',
    SWORD_AND_SHIELD_CROUCH: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouch.fbx',
    SWORD_AND_SHIELD_CROUCHING_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouching_2.fbx',
    SWORD_AND_SHIELD_CROUCHING_3: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouching_3.fbx',
    SWORD_AND_SHIELD_CROUCHING: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_crouching.fbx',
    SWORD_AND_SHIELD_DEATH_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_death_2.fbx',
    // SWORD_AND_SHIELD_DEATH: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_death.fbx',
    SWORD_AND_SHIELD_IDLE_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_idle_2.fbx',
    SWORD_AND_SHIELD_IDLE_3: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_idle_3.fbx',
    SWORD_AND_SHIELD_IDLE_4: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_idle_4.fbx',
    SWORD_AND_SHIELD_IDLE: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_idle.fbx',
    SWORD_AND_SHIELD_IMPACT_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_impact_2.fbx',
    SWORD_AND_SHIELD_IMPACT_3: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_impact_3.fbx',
    // SWORD_AND_SHIELD_IMPACT: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_impact.fbx',
    SWORD_AND_SHIELD_JUMP_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_jump_2.fbx',
    SWORD_AND_SHIELD_JUMP: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_jump.fbx',
    SWORD_AND_SHIELD_KICK: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_kick.fbx',
    SWORD_AND_SHIELD_POWER_UP: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_power_up.fbx',
    SWORD_AND_SHIELD_RUN_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_run_2.fbx',
    SWORD_AND_SHIELD_RUN: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_run.fbx',
    SWORD_AND_SHIELD_SLASH_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_2.fbx',
    SWORD_AND_SHIELD_SLASH_3: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_3.fbx',
    SWORD_AND_SHIELD_SLASH_4: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_4.fbx',
    // SWORD_AND_SHIELD_SLASH_5: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_slash_5.fbx',
    // SWORD_AND_SHIELD_SLASH: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_slash.fbx',
    SWORD_AND_SHIELD_STRAFE_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe_2.fbx',
    SWORD_AND_SHIELD_STRAFE_3: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe_3.fbx',
    SWORD_AND_SHIELD_STRAFE_4: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe_4.fbx',
    SWORD_AND_SHIELD_STRAFE: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_strafe.fbx',
    SWORD_AND_SHIELD_TURN_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_turn_2.fbx',
    SWORD_AND_SHIELD_TURN: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_turn.fbx',
    SWORD_AND_SHIELD_WALK_2: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_walk_2.fbx',
    SWORD_AND_SHIELD_WALK: 'assets/Pro_Sword_and_Shield_Pack/sword_and_shield_walk.fbx',
    SIT_TO_STAND: 'assets/Pro_Sword_and_Shield_Pack/sit_to_stand.fbx',
    STAND_TO_SIT: 'assets/Pro_Sword_and_Shield_Pack/stand_to_sit.fbx',
    SITTING_IDLE: 'assets/Pro_Sword_and_Shield_Pack/sitting_idle.fbx',
  },
  CAMPFIRE: 'assets/Map/h_campfire.glb',
  CASTLE_WALL: 'assets/Map/castle_wall.glb',
  TENT: 'assets/Map/tent_modified.glb',
  WOOD_BLOCK: 'assets/Map/wood_chopping_trunk_base.glb',
}
