/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\assets\Fanny\Fanny.glb -o .\src\components\canvas\Character\Character.tsx 
*/

import { Assets } from '@/helpers/assetMap'
import { Controls } from '@/helpers/constants'
import { useBoundStore } from '@/store/store'
import { OrbitControls, useFBX, useKeyboardControls } from '@react-three/drei'
import { useFrame, useLoader, useThree } from '@react-three/fiber'
import {
  CapsuleCollider,
  CuboidCollider,
  RapierRigidBody,
  RigidBody,
  euler,
  quat,
  useRapier,
  vec3,
} from '@react-three/rapier'
import { useControls } from 'leva'
import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import { FBXLoader, MMDLoader } from 'three-stdlib'
import Camera from './Camera/Camera'
import { useDebugMode } from '@/hooks/useDebugMode'
import { matchesGlob } from 'path'
import { useAnimationModel } from '@/hooks/useAnimationModel'
import characterSetting from '@/settings/df_character_setting.json'
import { mobileAndTabletCheck } from '@/helpers/mobileAndTabletCheck'
import { EGameMode } from '@/constant/enum'

console.log(characterSetting)
interface CharacterProps {
  // Add any props if needed
  orbit: boolean
}

const Character: React.FC<CharacterProps> = (props) => {
  const group = useRef(null)
  const nodes = useLoader(FBXLoader, Assets.CHARACTER)
  const setCharacter = useBoundStore((state) => state.setCharacter)
  const player = useRef<RapierRigidBody>(null)
  const { controls, camera, scene } = useThree((state) => state)
  const playerCollideHalfHeight = characterSetting.collision.halfHeight
  const { rapier, world } = useRapier()
  const isDebugMode = useDebugMode()
  // const { helmet, shield, sword } = useControls('Character Setting', {
  //   helmet: {
  //     value: true,
  //     label: 'Helmet',
  //   },
  //   shield: {
  //     value: true,
  //     label: 'Shield',
  //   },
  //   sword: {
  //     value: true,
  //     label: 'Sword',
  //   },
  // })

  const setPlayerRef = useBoundStore((state) => state.setPlayerRef)

  useEffect(() => {
    if (setPlayerRef) setPlayerRef(player)
  }, [player, setPlayerRef])

  const [subscribeKeys, getKeys] = useKeyboardControls()
  const followCameraFunc = useBoundStore((state) => state.followCameraFunc)
  const { actionMap, mixer, currentAction, setCurrentAction } = useAnimationModel({ player: nodes })
  // const fbxTemp = useFBX(Assets.ANIMATION.SWORD_AND_SHIELD_IDLE)

  useEffect(() => {
    if (nodes) {
      setCharacter(nodes)
    }
  }, [nodes, setCharacter])

  // hear jump key press
  useEffect(() => {
    const unSubscribeJumpKey = subscribeKeys(
      (state) => state.jump,
      (jump) => {
        if (jump) {
          jumpCharacter()
        }
      },
    )
    return () => {
      unSubscribeJumpKey()
    }
  }, [subscribeKeys])

  //tinh toan huong bu cua nhan vat
  /*               w
  pi/4   0(offset) -pi/4
  (a)  pi/2                     -pi/2 (d)
  3pi/4      pi    -3pi/4
  s                  */
  const directionOffset = ({
    forward,
    left,
    right,
    backward,
  }: {
    forward: boolean
    left: boolean
    right: boolean
    backward: boolean
  }) => {
    let directionOffset = 0
    if (forward) {
      if (left) {
        directionOffset = Math.PI / 4 //w+a
      } else if (right) {
        directionOffset = -Math.PI / 4 //w+d
      }
    } else if (backward) {
      if (left) {
        directionOffset = (3 * Math.PI) / 4 //s+a
      } else if (right) {
        directionOffset = (-3 * Math.PI) / 4 //s+d
      } else {
        directionOffset = Math.PI //s
      }
    } else if (left) {
      directionOffset = Math.PI / 2 //a
    } else if (right) {
      directionOffset = -Math.PI / 2 //d
    }
    return directionOffset
  }
  const rotateCharacter = ({
    forward,
    left,
    right,
    backward,
  }: {
    forward: boolean
    left: boolean
    right: boolean
    backward: boolean
  }) => {
    if (!player.current) return

    const rotateAngle = new THREE.Vector3(0, 1, 0)
    const rotateQuaternion = new THREE.Quaternion()
    const currentRotation = player.current.rotation()
    const quaternion = new THREE.Quaternion(currentRotation.x, currentRotation.y, currentRotation.z, currentRotation.w)
    const desiredQuaternion = directionOffset({ forward, left, right, backward })

    rotateQuaternion.setFromAxisAngle(rotateAngle, desiredQuaternion)
    quaternion.slerp(rotateQuaternion, 0.1)

    player.current.setRotation(quaternion, true)
  }
  const jumpTimeout = useRef<NodeJS.Timeout | null>(null)
  const jumpCharacter = () => {
    // Clear all pending timeouts
    if (idleTimeout.current) {
      clearTimeout(idleTimeout.current)
      idleTimeout.current = null
    }
    if (jumpTimeout.current) {
      clearTimeout(jumpTimeout.current)
      jumpTimeout.current = null
    }

    if (!player.current) return

    console.log('jumpCharacter')

    // nodes.children[1].material.transparent = true
    nodes.children[3].material.opacity = 0.5

    const originRayPosition = player.current.translation()

    originRayPosition.y -= 0.01

    const directionRayCast = vec3({ x: 0, y: -1, z: 0 })
    const maxTimeOfImpact = 10

    const ray = new rapier.Ray(originRayPosition, directionRayCast)
    const hit = world.castRay(ray, maxTimeOfImpact, true)

    if (hit?.timeOfImpact < 1) {
      const impulse = new THREE.Vector3(0, 220, 0)
      player.current.applyImpulse(impulse, true)
    }

    if (isDebugMode) {
      // Add debug logging
      console.log('Ray cast details:', {
        origin: originRayPosition,
        direction: directionRayCast,
        hit: hit,
        timeOfImpact: hit?.timeOfImpact,
        collider: hit?.collider,
      })
      const debugRay = new THREE.Line(
        new THREE.BufferGeometry().setFromPoints([
          new THREE.Vector3(originRayPosition.x, originRayPosition.y, originRayPosition.z),
          new THREE.Vector3(originRayPosition.x, originRayPosition.y - maxTimeOfImpact, originRayPosition.z),
        ]),
        new THREE.LineBasicMaterial({ color: 0xff0000 }),
      )
      scene.add(debugRay)
      // Remove the debug ray after 1 second
      setTimeout(() => {
        scene.remove(debugRay)
      }, timeToIdle)
    }

    // Play jump animation ONCE and clamp when finished
    const jumpAction = actionMap.get(characterSetting.animation.jump.name)
    if (jumpAction) {
      jumpAction.reset()
      jumpAction.setLoop(THREE.LoopOnce, 1)
      jumpAction.clampWhenFinished = true
      jumpAction.fadeIn(0.15).play()
    }
    setCurrentAction(characterSetting.animation.jump.name)

    // Set jump timeout to return to idle after jump animation
    const jumpDuration = jumpAction?.getClip().duration ?? 1
    jumpTimeout.current = setTimeout(() => {
      const keys = getKeys()
      const isMoving = keys.forward || keys.back || keys.left || keys.right
      if (isMoving) {
        setCurrentAction(characterSetting.animation.walk.name)
      } else {
        setCurrentAction(characterSetting.animation.idle.name)
      }
      jumpTimeout.current = null
    }, jumpDuration * 1000)
  }

  // TODO: solve move character and camera direction
  const moveCharacter = ({ forward, back, left, right, deltaTime }) => {
    if (!player.current) return
    const maxSpeed = characterSetting.control.normalSpeed
    const velocity = player.current.linvel()

    // 1. Get camera's forward and right vectors (projected to XZ)
    const cameraDirection = new THREE.Vector3()
    camera.getWorldDirection(cameraDirection)
    cameraDirection.y = 0
    cameraDirection.normalize()

    const cameraRight = new THREE.Vector3()
    cameraRight.crossVectors(cameraDirection, new THREE.Vector3(0, 1, 0)).normalize()

    // 2. Build movement direction
    let moveDir = new THREE.Vector3()
    if (forward) moveDir.add(cameraDirection)
    if (back) moveDir.sub(cameraDirection)
    if (left) moveDir.sub(cameraRight)
    if (right) moveDir.add(cameraRight)

    if (moveDir.lengthSq() > 0) {
      moveDir.normalize()
      // 3. Set velocity in the direction
      moveDir.multiplyScalar(maxSpeed)
      player.current.setLinvel({ x: moveDir.x, y: velocity.y, z: moveDir.z }, true)

      // 4. Rotate player to face movement direction
      const targetRotation = Math.atan2(moveDir.x, moveDir.z)
      const currentRotation = player.current.rotation()
      const quaternion = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), targetRotation)
      player.current.setRotation(quaternion, true)

      setCurrentAction(characterSetting.animation.walk.name)
    }
  }
  const isMb = mobileAndTabletCheck()

  const idleTimeout = useRef<NodeJS.Timeout | null>(null)
  const timeToIdle = isMb ? characterSetting.control.timeToIdle.MB : characterSetting.control.timeToIdle.PC
  const prevKeys = useRef({ forward: false, back: false, left: false, right: false, jump: false })
  const gameMode = useBoundStore((state) => state.game.mode)

  useFrame((state, delta) => {
    const keys = getKeys()
    const isMoving = keys.forward || keys.back || keys.left || keys.right
    const wasMoving =
      prevKeys.current.forward || prevKeys.current.back || prevKeys.current.left || prevKeys.current.right

    if (isMoving && !wasMoving) {
      // Started moving
      if (idleTimeout.current) {
        clearTimeout(idleTimeout.current)
        idleTimeout.current = null
      }
      // --- FIX: Interrupt jump if moving during jump ---
      if (jumpTimeout.current) {
        clearTimeout(jumpTimeout.current)
        jumpTimeout.current = null
        if (currentAction === characterSetting.animation.jump.name) {
          setCurrentAction(characterSetting.animation.walk.name)
        }
      }
      if (currentAction !== characterSetting.animation.walk.name) {
        setCurrentAction(characterSetting.animation.walk.name)
      }
    } else if (!isMoving && wasMoving) {
      // Stopped moving
      if (player.current) {
        player.current.setLinvel({ x: 0, y: player.current.linvel().y, z: 0 }, true)
      }
      const walkAction = actionMap.get(characterSetting.animation.walk.name)
      if (walkAction) {
        walkAction.setLoop(THREE.LoopOnce, 1)
        walkAction.clampWhenFinished = true
        if (!walkAction.isRunning()) {
          walkAction.reset().play()
        }
      }
      // Only set to idle after a timeout
      idleTimeout.current = setTimeout(() => {
        setCurrentAction(characterSetting.animation.idle.name)
        idleTimeout.current = null
      }, timeToIdle)
    }
    if (isMoving) {
      rotateCharacter({
        forward: keys.forward,
        left: keys.left,
        right: keys.right,
        backward: keys.back,
      })
      moveCharacter({
        forward: keys.forward,
        back: keys.back,
        left: keys.left,
        right: keys.right,
        deltaTime: delta,
      })
    }
    // follow camera
    if (followCameraFunc) {
      if (props.orbit) {
        return
      }
      followCameraFunc(delta)
    }

    mixer.update(delta)
    prevKeys.current = keys
  })

  return (
    <group ref={group} {...props} dispose={null} rotation={[0, 0, 0]}>
      <Camera
        player={player}
        // colliderPosition={[
        //   characterSetting.startPosition.x,
        //   characterSetting.startPosition.y ,
        //   characterSetting.startPosition.z,
        // ]}
      />
      <RigidBody
        canSleep={false}
        colliders={false}
        ref={player}
        lockRotations={true}
        position={[
          characterSetting.startPosition.x,
          characterSetting.startPosition.y,
          characterSetting.startPosition.z,
        ]}
      >
        <primitive
          object={nodes}
          scale={0.1}
          position={[0, 0, 0]}
        ></primitive>
        {/* <mesh geometry={nodes.children[0].geometry} material={nodes.children[0].material} scale={0.1}></mesh> */}
        {/* {helmet && (
          <mesh geometry={nodes.children[1].geometry} material={nodes.children[1].material} scale={0.1}></mesh>
        )}
        {shield && (
          <mesh geometry={nodes.children[2].geometry} material={nodes.children[2].material} scale={0.1}></mesh>
        )}
        <mesh geometry={nodes.children[3].geometry} material={nodes.children[3].material} scale={0.1}></mesh>
        {sword && <mesh geometry={nodes.children[4].geometry} material={nodes.children[4].material} scale={0.1}></mesh>} */}

        <CapsuleCollider
          args={[playerCollideHalfHeight, characterSetting.collision.radius]}
          mass={50}
          position={[0, playerCollideHalfHeight + characterSetting.collision.radius, 0]}
          friction={1}
          restitution={0}
          linearDamping={1}
          angularDamping={1}
        />
      </RigidBody>
    </group>
  )
}

export default Character
